export const timelineEventsHighlight = [
	{
		id: 0,
		title: "Ontario College Diploma",
		date: "April 2024",
		description: "Web Development",
		icon: "../icons/graduation-cap.svg",
		location: "Durham College, Oshawa ON",
		color: "purple",
		type: "education",
	},
	{
		id: 1,
		title:
			"Bachelor of Information Technology, Game Development and Entrepreneurship",
		date: "April 2022",
		description: "Game Development and Entrepreneurship",
		icon: "../icons/graduation-cap.svg",
		location: "Ontario Tech University ,Oshawa ON",
		color: "purple",
		type: "education",
	},
	{
		id: 2,
		title: "Game Developer, Department of National Defense, Government of Canada",
		date: "May 2022 - September 2022",
		description: "Department of National Defense, Government of Canada",
		icon: "../icons/briefcase.svg",
		location: "Remote from Halifax, NS",
		color: "red",
		type: "work",
	},
	{
		id: 4,
		title:
			"Mental Health First Aid Certificate, Mental Health Commission of Canada",
		date: "June 2019",
		description: "Mental Health Commission of Canada",
		icon: "../icons/graduation-cap.svg",
		location: "Oshawa, ON",
		color: "purple",
		type: "certification",
	},
	{
		id: 3,
		title: "Dialectical Behavioral Therapy",
		date: "May 2022",
		description: "",
		icon: "../icons/brain.svg",
		location: "Ontario Shores, Whitby, ON",
		color: "yellow",
		type: "other",
	},
];
timelineEventsHighlight.sort((a, b) => (a.id > b.id ? 1 : -1));

export const allTimelineEvents = [
	{
		id: 0,
		title: "Ontario College Diploma",
		date: "Sept 2022 - April 2024",
		description: "Web Development",
		points: ["College Honour Roll, Fall 2022, Winter 2023, Fall 2023."],
		icon: "../icons/graduation-cap.svg",
		location: "Durham College, Oshawa ON",
		color: "purple",
		type: "education",
	},
	{
		id: 1,
		title: "Bachelor of Information Technology",
		date: "Sept 2018 - April 2022",
		description: "Game Development and Entrepreneurship",
		points: [
			"Liaison for Game Development Society, 2019.",
			"Graduated with Distinction.",
		],
		icon: "../icons/graduation-cap.svg",
		location: "Ontario Tech University ,Oshawa ON",
		color: "purple",
		type: "education",
	},
	{
		id: 2,
		title: "Game Developer",
		date: "May 2022 - September 2022",
		description: "Department of National Defense, Government of Canada",
		points: [
			"Programed in the language C#, using the engine, Unity.",
			"Traversed and developed on an existing project, with little documentation.",
			"Developed training scenarios in the Navy’s Virtual fleet, specializing in auditory scenarios.",
			"Assisted in the design of training scenarios.",
			"Collaborated with other developers in the creation of training scenarios.",
		],
		icon: "../icons/briefcase.svg",
		location: "Remote from Halifax, NS",
		color: "red",
		type: "work",
	},
	{
		id: 3,
		title: "Dialectical Behavioral Therapy",
		date: "May 2022",
		description: "",
		points: ["DBT Skills Training, Ontario Shores, Whitby, ON"],
		icon: "../icons/brain.svg",
		location: "Ontario Shores, Whitby, ON",
		color: "yellow",
		type: "other",
	},
	{
		id: 4,
		title: "Web Developer / Media Assistant",
		date: "Sept 2023 - April 2024",
		description: "Professional and Part-Time Learning",
		points: [
			"Transferring course content into HTML and CSS (Bootstrap) templates.",
			"Formatting templates to be visually appealing.",
			"Using D2L, the Online Learning Platform, to implement course content.",
			"Edit videos using Premiere Pro, for the PPL YouTube channel.",
			"Assist with the filming of student interviews at events.",
		],
		icon: "../icons/briefcase.svg",
		location: "Durham College, Oshawa, ON",
		color: "red",
		type: "work",
	},
	{
		id: 5,
		title: "Freelance Online Presence & Web Developer",
		date: "April 2023 - June 2024",
		description: "",
		points: [
			"Headed development and ongoing management of avidlegalservices.com, an informative WordPress site for a paralegal start-up.",
			"Formulated legal components: privacy policy, cookie policy, accessibility statement, terms of use, and disclaimer, adhering to Canadian web regulations.",
			"Executed an optimization strategy, enhancing website usability, SEO performance, loading speed, and accessibility to meet WCAG 2.1 AA standards.",
			"Established a social media presence on Instagram and Facebook, enhancing brand visibility and engagement.",
			"Created distinctive brand identity, encompassing logo, essential assets, and promotional materials like business cards, flyers, and stickers.",
		],
		icon: "../icons/briefcase.svg",
		location: "AVID Legal Services, Whitby, ON",
		color: "red",
		type: "work",
	},
	{
		id: 6,
		title: "Web Developer",
		date: "Jan 2023 - April 2024",
		description: "Founder's Drive",
		points: [
			"Created and currently managing foundersdrive.com, a WordPress-based website for a start-up entrepreneurship podcast, incorporating external HTML, CSS, and PHP expertise.",
			"Implemented an optimization strategy, elevating website usability, SEO performance, loading speed, and accessibility to align seamlessly with WCAG 2.1 AA standards.",
			"Utilizing Google Analytics to track website views and trends.",
			"Worked with a team to implement provided content and design.",
		],
		icon: "../icons/briefcase.svg",
		location: "Durham College, Oshawa, ON",
		color: "red",
		type: "work",
	},
	{
		id: 7,
		title: "Campus ID Assistant",
		date: "Sept 2022 - April 2023",
		description: "Founder's Drive",
		points: [
			"Utilized Campus ID (Touchnet VIP) and UPass (Bytemark, Presto Voucher Portal) systems to troubleshoot student ID related issues.",
			"Responded to student Campus ID and UPass related e-mail inquiries.",
			"Printed Student ID Cards, Badges, Staff Proximity cards.",
			"Responded to in-person student inquiries during peak hours.",
		],
		icon: "../icons/briefcase.svg",
		location: "Durham College, Oshawa, ON",
		color: "red",
		type: "work",
	},
	{
		id: 8,
		title: "Jr Business Support Analyst",
		date: "June 2020 - April 2022",
		description: "",
		points: [
			"Researched best business practices in Banner of other universities regarding student satisfaction and enrollment.",
			"Evaluated and removed of redundant features on school platform.",
			"Provided system training and troubleshooting services for the university’s learning management system, Canvas.",
			"Identified issues, analyzed information, and provided solutions to problems with the university’s enterprise resource planning system, Banner.",
			"Created videos and interactive demos for students and faculty regarding both Banner and Canvas.",
		],
		icon: "../icons/briefcase.svg",
		location: "Ontario Tech University, Oshawa, ON",
		color: "red",
		type: "work",
	},
	{
		id: 9,
		title: "ID Services Assistant",
		date: "June 2019 - April 2020",
		description: "",
		points: [
			"Assisted in creating faculty, staff, and student identification (ID) cards and badges.",
			"Worked at university events including move-in weekend to help students get their ID cards.",
			"Conducted research, gathered information from multiple sources and presented results",
			"Received and processed stock into inventory management system.",
		],
		icon: "../icons/briefcase.svg",
		location: "Ontario Tech University, Oshawa, ON",
		color: "red",
		type: "work",
	},
	{
		id: 10,
		title:
			"Mental Health First Aid Certificate, Mental Health Commission of Canada",
		date: "June 2019",
		description: "Mental Health Commission of Canada",
		points: [
			"Practiced awareness of signs and symptoms of the most common mental health problems.",
			"Learned how to interact with and provide help to individuals experiencing a mental health problem or crisis.",
			"Practiced crisis first aid skills.",
		],
		icon: "../icons/graduation-cap.svg",
		location: "Oshawa, ON",
		color: "purple",
		type: "certification",
	},
	{
		id: 12,
		title: "Math Peer Tutor",
		date: "2017 - 2018",
		description: "O'Neil Collegiate and Vocational Institute",
		points: [
			"Created personalized education plans to assist students who required a peer tutor.",
			"Ran math support discussions for groups of 20 to 25 students.",
			"Marked assignments and kept detailed records of course work.",
			"Helped foster and maintain an inclusive and positive learning atmosphere.",
		],
		icon: "../icons/graduation-cap.svg",
		location: "Oshawa, ON",
		color: "purple",
		type: "volunteer",
	},
	{
		id: 11,
		title: "Community Volunteer",
		date: "2018 - 2019",
		description: "Oshawa Community Church",
		points: [
			"Assisted in planning and oversight of community outreach events.",
			"Programmed weekly electronic elements and backups for community presentations.",
			"Ran technology workshops for community members. ",
			"Planned and facilitated group discussions on a variety of topics ages 12 to 18.",
		],
		icon: "../icons/graduation-cap.svg",
		location: "Oshawa, ON",
		color: "purple",
		type: "volunteer",
	},
];
allTimelineEvents.sort((a, b) => (a.id > b.id ? 1 : -1));

const projects = [
	{
		title: "",
		type: "",
		teamSize: 1,
		duration: "",
		description: "",
		role: "",
		tools: [],
		githubLink: "",
		projectLink: "",
		image: "",
		date: "",
	},
	{
		title: "Cat Collecter",
		type: "Game",
		teamSize: 1,
		duration: "7 Days",
		description:
			"You are now the cat collecter! How many cats can you collect in 10 turns? Yes I spelled collector wrong, of course it was on purpose.",
		role: "Sole Developer",
		tools: [],
		githubLink: "https://github.com/kenningtonz/Cat-Collecter",
		projectLink: "https://kenningtonz.itch.io/cat-collecter",
		image: "",
		date: "",
	},
];
